name: Policy Compliance

on:
  push:
  pull_request:

jobs:

  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: docker://ghcr.io/policy-as-versioned-code/policy-checker:latest

