name: Policy Compliance

on:
  push:
  pull_request:

jobs:

  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: docker://ghcr.io/policy-as-versioned-code/policy-checker:latest

